### ISSUE TITLE
爬取股票数据失败

### ISSUE THREAD

**Issue by mmtun** [piginzoo/fund_analysis#3]
执行命令：

`bin/crawler.sh --code 688157 --type stock`

console中输入失败信息如下：

`取 <代码>，代码：--code 688157 --type stock
/Users/zhangxiaojing/dev/fund_analysis/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py:182: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if entities is not ():
提示：当前环境 pandas 版本高于 0.25，get_price 与 get_fundamentals_continuously 接口 panel 参数将固定为 False
注意：0.25 以上版本 pandas 不支持 panel，如使用该数据结构和相关函数请注意修改
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/zhangxiaojing/dev/fund_analysis/fund_analysis/crawler/main.py", line 37, in <module>
    crawler = JQDataStockCrawler()
  File "/Users/zhangxiaojing/dev/fund_analysis/fund_analysis/crawler/stock/crawler_jqdata_stock.py", line 16, in __init__
    jqdata_utils.login()
  File "/Users/zhangxiaojing/dev/fund_analysis/fund_analysis/tools/jqdata_utils.py", line 10, in login
    conf = utils.load_config()
  File "/Users/zhangxiaojing/dev/fund_analysis/fund_analysis/tools/utils.py", line 36, in load_config
    raise ValueError("指定的环境配置文件不存在:" + const.CONF_PATH)
ValueError: 指定的环境配置文件不存在:conf/config.yml`

**Comment by mmtun** [comment]
已经确认是由于const.py文件中定义的配置文件找不到引起的问题。

我修改了代码，需要使用绝对路径才可以，是不是我命令执行的起势目录位置不对？

**Comment by mmtun** [comment]
修改代码，使用绝对路径解决问题。

**Comment by piginzoo** [comment]
赞，这个文件我在说明里提到了，但是确实应该像你那样，给一个sample文件出来，你的代码已经merge进来了
